---
- hosts: all
  vars:
    favcolor: blue
  vars_files:
    - ./vars.yml
  pre_tasks:
    - name: Who is running the update
      become: false
      local_action: command whoami
      register: whoami
    - name: Announce start to slack
      uri:
        url: "{{ slack_webhook }}"
        method: POST
        body: '{"text":"[ansible][*{{inventory_hostname}}*] {{whoami.stdout}} running nginx magic! :rocket: "}'
        status_code: 200
        body_format: json
      delegate_to: localhost
      become: no
      # https://docs.ansible.com/ansible/2.5/user_guide/playbooks_checkmode.html#information-about-check-mode-in-variables
      ignore_errors: "{{ ansible_check_mode }}"

  post_tasks:
    - name: Announce finish to slack
      uri:
        # webhook for #sre-feed
        url: "{{ slack_webhook }}"
        method: POST
        body: '{"text":"[ansible][*{{inventory_hostname}}*] {{whoami.stdout}} completed rebooting the host"}'
        status_code: 200
        body_format: json
      delegate_to: localhost
      become: false
  roles:
    - { role: ./roles/nginx }
